### ISSUE TITLE
Eloquent way to query /api/graphql

### ISSUE THREAD

**Issue by kalyncoose** [Flux159/next-postgraphile#11]
Hey @Flux159! Thank you for this awesome starter example!

I have successfully implemented Postgraphile in the most recent nextjs version [in my repo here](https://github.com/testctrl/testctrl).

Since you did not have a specific example of how to query `/api/graphql`, I used [Vercel's example here](https://github.com/vercel/next.js/blob/canary/examples/api-routes-graphql/pages/index.tsx) which uses their SWR fetch tool.

My postgresdb has a table `agile_teams` with this:
![image](https://user-images.githubusercontent.com/65800415/216939004-ca0074dc-612e-4982-b3e5-105427558600.png)

With the graphiql tool I created a query from the generated postgraphile:
```graphql
query MyQuery {
  allAgileTeams {
    edges {
      node {
        id
        name
        domain
        art
      }
    }
  }
}
```

In my nextjs page I created a type for the SWR fetch tool to use for typing:
```ts
type Data = {
  allAgileTeams: {
    edges: {
      node: {
        id: number
        name: string
        art: string
        domain: string
      }
    }[]
  }
}
```
Now in order to use the data I have to iterate over the edges under the data type:
```tsx
<div>
  {allAgileTeams.edges.map((team, index) => (
    <div key={index}>
      <br />
      ID: {team.node.id} <br />
      Name: {team.node.name} <br />
      ART: {team.node.art} <br />
      Domain: {team.node.domain} <br />
    </div>
  ))}
</div>
```
Which looks like this in my app:
![image](https://user-images.githubusercontent.com/65800415/216939892-2433cd11-85aa-4b47-8168-fc7bf993eadc.png)

***My question is***: do you have a better/more eloquent way to do this? With or without having to declare a type? A different query/fetch middleware/tool? Any suggestions are appreciated!

**Comment by Flux159** [comment]
Hi, I'm using Apollo (`@apollo/client` in [npm](https://www.npmjs.com/package/@apollo/client)) in my app built using the same stack as this repo. You can read the docs here: https://www.apollographql.com/docs/react/api/react/hooks/ 

Essentially, in `pages/_app.tsx`, create a client that points to your endpoint (use a config/environment variable that determines between prod vs local). Something similar to this:
```
const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: "http://localhost:3000/api/graphql"
});

export default class App extends NextApp<AppInitialProps> {
  render(): JSX.Element {
    const { Component, pageProps } = this.props;
    return (
      // @ts-ignore
      <ApolloProvider client={client}>
        <Component {...pageProps} />
      </ApolloProvider>
    );
  }
}
```

Then in any React component, you should be able to `useClient` to run queries and mutations:
```
import { gql, useQuery } from '@apollo/client';

const GET_GREETING = gql`
  query GetGreeting($language: String!) {
    greeting(language: $language) {
      message
    }
  }
`;

function Hello() {
  const { loading, error, data } = useQuery(GET_GREETING, {
    variables: { language: 'english' },
  });
  if (loading) return <p>Loading ...</p>;
  return <h1>Hello {data.greeting.message}!</h1>;
}
```

Note that by default `useQuery` will be `any` typed, you still need to write the types of your responses if you want typescript to properly type check. If you want autogeneration of types, you would probably want to look at something like [prisma](https://www.prisma.io/), but that's an entirely different ORM system than using postgraphile (I'm using prisma these days in a larger project since it also handles migrations & works very well for managing conflicts between developers).

Also, this repo is a bit old & hasn't been updated, next 13 allows functional components for `_app.tsx`. I would recommend starting from a new `create-next-app` if making a new project.

**Comment by kalyncoose** [comment]
Awesome, thank you for your incredible insight! I'll definitely research prisma vs postgraphile now that you mentioned the differences. Cool stuff!
